version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    restart: no

  db:
    image: postgres:16.4-bookworm
    volumes:
      - blog_api_django_pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=blog_api_django
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  blog_api_django_pg_data: